### ISSUE TITLE
小白编译openwrt出现错误

### ISSUE THREAD

**Issue by 1278136080** [wongsyrone/LinuxNotes#21]
huihui@huihui-PC:~/openwrt/openwrt$ make V=99 2>&1 |tee build.log |grep -i error
  HOSTCC  tools/lib/libfdt/fdt_strerror.o
/home/huihui/openwrt/openwrt/build_dir/host/u-boot-2014.10/lib/rsa/rsa-sign.c:279:21: error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'
make[5]: *** [tools/lib/rsa/rsa-sign.o] Error 1
make[4]: *** [tools-only] Error 2
make[3]: *** [/home/huihui/openwrt/openwrt/build_dir/host/u-boot-2014.10/.built] Error 2
make[2]: *** [tools/mkimage/compile] Error 2
make[1]: *** [/home/huihui/openwrt/openwrt/staging_dir/target-mips_34kc_musl-1.1.14/stamp/.tools_install_yynyynynynyyyyyyynyyyyyyyyyyyyynyyyyynnyynynyyyynnnyy] Error 2
make: *** [world] Error 2

**Comment by wongsyrone** [comment]
openwrt已经过时了，现在都用LEDE
